service: get-calendar-events

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:state, 'dev'}
  region: us-east-1

functions:
  index:
    handler: handlers/index.index
    events:
      - http: "GET /"

plugins:
  - serverless-offline
  - serverless-plugin-typescript
